### ISSUE TITLE
[Feature Request] Module Vanilla Plus

### ISSUE THREAD

**Issue by BijuuKrunos** [BananaPuncher714/Cartographer2#15]
Hey there, it would be cool, if the deathpoint is on the Map, until the player found in a range from X blocks the deathpoint location.
And that the Deathpoints are saved to a file or something like that, because now the deathpoint is not there anymore after server restart.

thx and great work.

Greetz Krunos

**Comment by BananaPuncher714** [comment]
Valid points, I'll see what I can do.

**Comment by BananaPuncher714** [comment]
It should be added now, I'll be closing this soon unless it's still not implemented.
