### ISSUE TITLE
[Feature Request] GriefDefender Support

### ISSUE THREAD

**Issue by ahdg6** [BananaPuncher714/Cartographer2#17]
It would be awesome to add support of GriefDefender.
API: https://github.com/bloodmc/GriefDefenderAPI/

**Comment by BananaPuncher714** [comment]
Sure, I can take a look at this when I have time or update Cartographer.

**Comment by ahdg6** [comment]
There is an example for Pl3x-Map:https://github.com/Tartaros-Gamer/Pl3xMap-GriefDefender/tree/master/src/main/java/net/pl3x/map/griefdefender
I don't know whether it will be helpful for you or not,
By the way,thanks for adopt my request.

**Comment by BananaPuncher714** [comment]
Yes, this will be very helpful in using the API. Thanks!

**Comment by ahdg6** [comment]
https://github.com/ahdg6/Cartographer2/commit/136d53847bad30c05f8285b9251586ad380ea934
