### ISSUE TITLE
Support for version 1.9.2

### ISSUE THREAD

**Issue by Doomshade** [BananaPuncher714/Cartographer2#19]
Hi! Would you be kind to add support for bukkit/spigot version 1.9.2? We are currently running spigot 1.9.2 instead of 1.9.4 as some of our plugins are dependant on that specific version. We can't move higher due to the fact that the plugins are no longer in development :/

I hope it's not a big issue for you.

Kind Regards,
Doomshade

**Comment by Doomshade** [comment]
As far as I see it can be done fairly easily if you just copy the 1_9_R2 NMSHandler version and make a new 1_9_R1 one.

**Comment by BananaPuncher714** [comment]
Yes, I'll be sure to do that.
