### ISSUE TITLE
Add 1.19 Support

### ISSUE THREAD

**Issue by tyepavitt** [BananaPuncher714/Cartographer2#24]
[Server thread/INFO]: [Cartographer2] Enabling Cartographer2 v2.15.4
[Server thread/INFO]: [Cartographer2] Loading locales...
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loading default locale
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Successfully loaded the internal locale(default)
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language Català (Espanya)(Spain) as ca_es
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language ?eština (CS)(?esko) as cs_cz
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language Deutsch (DE)(Deutschland) as de_de
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language Pirate Speak(The Seven Seas) as en_pt
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language English (US)(USA) as en_us
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language Español (España)(Spain) as es_es
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language Filipino (PH)(Philippines) as fil_ph
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language Français (FR)(France) as fr_fr
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language Magyar(Hungary) as hu_hu
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language Bahasa Indonesia (Indonesia)(Indonesia) as id_id
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language Italiano(Italy) as it_it
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language ??? (Nihongo)(??) as ja_jp
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language ??????? (Kharthuli)(Georgia) as ka_ge
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language ???(South Korea) as ko_kr
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language Nederlands (NL)(Nederlands) as nl_nl
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language Polski(Poland) as pl_pl
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language Portugues(BR) as pt_br
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language Romanian (RO)(ROMANIA) as ro_ro
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language ??????? (Russki?)(Russia) as ru_ru
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language Sloven?ina (Slovensko)(Slovensko) as sk_sk
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language Turkish (TR)(Turkey) as tr_tr
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language Ti?ng Vi?t (VN)(Vi?t Nam) as vi_vn
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language Ti?ng Vi?t (VN)(Vi?t Nam) as vn_vn
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language ???? (??)(????) as zh_cn
[Server thread/INFO]: [LocaleManager] [Cartographer2] [LocaleManager] Loaded language ???? (??)(Taiwan, Hong Kong, Macau) as zh_tw
[Server thread/ERROR]: [Cartographer2] This version(v1_19_R1) is not supported currently!
[Server thread/ERROR]: [Cartographer2] Disabling plugin...
[Server thread/INFO]: [Cartographer2] Disabling Cartographer2 v2.15.4
[Server thread/INFO]: [Cartographer2] Disabling modules...
[Server thread/INFO]: [Cartographer2] Saving map data. This may take a while...
[Server thread/INFO]: [Cartographer2] Saving map data complete!
[Server thread/INFO]: [Cartographer2] Saving player data...
[Server thread/INFO]: [Cartographer2] Saving player data complete!

**Comment by BananaPuncher714** [comment]
Thanks for the heads up. I'll try to update it soon, but I don't have an ETA.

**Comment by BananaPuncher714** [comment]
Added support with 9290116357ebb683bbd657dfad5ab4716c19a1b3
