### ISSUE TITLE
Wrong NMS Handler in 1.12.2

### ISSUE THREAD

**Issue by Han4sak1** [BananaPuncher714/Cartographer2#33]
Happens when using 1.12.2 to boot the plugin

java.lang.NoClassDefFoundError: io/github/bananapuncher714/cartographer/core/implementation/v1_12/NMSHandler

should be v1_12_R1/NMSHandler

Only in recent versions, in old versions things are fine. Not sure if this happens after which version yet.

**Comment by BananaPuncher714** [comment]
Was this still an issue? I'd like to take a look at this if you have more detail(such as what server software you're using, etc)
