### ISSUE TITLE
IllegalStateException: Cannot encode empty ItemStack

### ISSUE THREAD

**Issue by RedstoneFuture** [BananaPuncher714/Cartographer2#35]
I get the following warning regularly: https://bytebin.lucko.me/V5XICJLuXS
Unfortunately, I don't yet know which item triggers this problem or how to replicate it.

- Cartographer2 v. 2.15.11
- ProtocolLib v. 5.3.0-SNAPSHOT-732
- PaperMC 1.21.1, build 123

**Comment by BananaPuncher714** [comment]
Thanks, this appears to be caused when you press "Q" with an empty hand. This error should be safe to ignore. I'll fix it on the next update.
