### ISSUE TITLE
How to build package

### ISSUE THREAD

**Issue by aviallon** [BananaPuncher714/Cartographer2#5]
Hello, sorry for troubling you.

I tried to compile your plugin using Maven, by doing :
```
mvn install
```
However, I'm stuck at a dependency problem :
```text
[ERROR] Failed to execute goal on project Cartographer2_Main: Could not resolve dependencies for project io.github.bananapuncher714:Cartographer2_Main:jar:2: The following artifacts could not be resolved: org.spigotmc:spigot:jar:1.15.1-R0.1-SNAPSHOT, io.github.bananapuncher714:NBTEditor:jar:7.13, com.wimbli.WorldBorder:WorldBorder:jar:1.9.10 (beta): Failure to find org.spigotmc:spigot:jar:1.15.1-R0.1-SNAPSHOT in https://repo.codemc.org/repository/maven-public was cached in the local repository, resolution will not be reattempted until the update interval of CodeMC has elapsed or updates are forced
```

Could you describe how you build it ? Perhaps I need to manually add all dependencies...

**Comment by aviallon** [comment]
Forgive me, I'm stupid

**Comment by BananaPuncher714** [comment]
You'll need to use BuildTools to build each version of spigot so that it adds them to your local repository.

**Comment by aviallon** [comment]
I fixed it. I still have issues with WorldBorder though, I can't find any working Maven repo for it.

**Comment by BananaPuncher714** [comment]
You'll need to clone and install it to your local repository as well.
